trigger:
  branches:
    include:
      - main
  paths:
    include:
      - external/llvm

pool: Linux1ESPool

steps:
- script: |
    git submodule init
    git submodule update
  displayName: Pull submodules
  workingDirectory: "$(Build.SourcesDirectory)"

- task: Docker@2
  displayName: Build and push to $(CONTAINER_REGISTRY)
  inputs:
    command: buildAndPush
    containerRegistry: $(CONTAINER_REGISTRY_SERVICE_CONNECTION)
    dockerfile: $(Build.SourcesDirectory)/.azure/manylinux/Dockerfile
    repository: accera-llvm-manylinux2014
    tags: |
      $(Build.BuildId)
      latest
    buildContext: "$(Build.SourcesDirectory)"